<a href="https://colab.research.google.com/github/mrpavankumar15/pytorch_avyu/blob/main/Pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Wed Aug  6 15:12:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

print("hello i am pavan for pytorch")

In [ ]:
## pytorch fundamentals ##

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
## introduction to tensors
## the tensors are created using torch.tensor()
## scalar - type
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
 scalar.ndim

0

In [ ]:
# get the tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
print(vector)
vector.ndim

tensor([7, 7])


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
## Matrix
matrix = torch.tensor([[2,3],[5,6]])
print(matrix)
print("size " ,matrix.shape)
print("ndim : ",matrix.ndim)
matrix[1]

tensor([[2, 3],
        [5, 6]])
size  torch.Size([2, 2])
ndim :  2


tensor([5, 6])

In [ ]:
## Tensor
tensor = torch.tensor([[[1,2,3],[3,4,5],[4,4,4]]])
print("tensor shape " ,tensor.shape)
print("ndim ", tensor.ndim)
print(tensor)
# print index value
print("the index valued : ",tensor[0,2])
print("the all values : ")
tensor[0]


tensor shape  torch.Size([1, 3, 3])
ndim  3
tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 4, 4]]])
the index valued :  tensor([4, 4, 4])
the all values : 


tensor([[1, 2, 3],
        [3, 4, 5],
        [4, 4, 4]])

## Random tensors

why randome tensors ?
random tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better representation

start with random number -> look at data -> update numbers

In [ ]:
# create random tensors of shape or size
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5704, 0.0555, 0.3710, 0.2147],
        [0.0863, 0.1746, 0.0141, 0.1205],
        [0.8275, 0.4222, 0.7574, 0.1347]])

In [ ]:
random_image  =  torch.rand(size=(3,224,224))
random_image.shape, random_image.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
## create tensor with all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
## create tensor with all ones
ones = torch.ones(size=(3,4))
## it tells the data type
print(ones.dtype)
ones

torch.float32


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
##range of tensors and tensors-like
## torch.range() or torch.arange()
torch.range(0,10)
 ## or ##


/tmp/ipython-input-302490603.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_ten = torch.arange(1,11)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
oneTo_1000 = torch.arange(start=0 , end = 1000 , step = 100)
oneTo_1000

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [ ]:
## creating tensors like
## use zeros_like
ten_zeros = torch.zeros_like(input=oneTo_1000)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note: ** Tensor datatypes is one of the 3 big erros you'll run into with pytorch & deep learning:

1.Tensors not right datatype

2.Tensors not right shape

3.Tensors not on the right device

In [ ]:
float_32 = torch.tensor([3.0 , 6.0 , 9.0],
                        dtype =None , #what data type is tensor
                        device=None, #what device are you using like cpu or gpu
                        requires_grad=False) # whether or not to track gradients with this operations


float_32

tensor([3., 6., 9.])

In [ ]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
## Tensor attributes

int_32_tensor = torch.tensor([2,4,6] ,dtype=torch.int32)
int_32_tensor

tensor([2, 4, 6], dtype=torch.int32)

In [3]:
## getting information from the tensors (tensor attributes)

## datatype - tenor.dtype
## shape - tensor.shape
## device - tensor.device
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"datatype of tensor : {some_tensor.dtype}")
print(f"shape of tensor : {some_tensor.shape}")
print(f"device of tensor : {some_tensor.device}")



tensor([[0.6744, 0.0170, 0.1936, 0.5063],
        [0.3589, 0.2443, 0.4098, 0.6870],
        [0.9800, 0.0961, 0.9857, 0.5532]])
datatype of tensor : torch.float32
shape of tensor : torch.Size([3, 4])
device of tensor : cpu


## Manipulation tensors

Tensors operations include:

* Addition
* Substraction
* Multiplication
* Division
* Matrix Multiplication

In [3]:
#create a tensor
tensor = torch.tensor([1,2,3])

## addition
tensor + 10


tensor([11, 12, 13])

In [7]:
## multiplication
tensor = tensor * 10
tensor

tensor([100, 200, 300])

In [6]:
## subtraction
tensor -10

tensor([ 0, 10, 20])

In [12]:
# tryout pytorch inbuilt functions

torch.mul(tensor[0] , 100)
# addition
print(tensor.add(10))

tensor([110, 210, 310])


### Matrix Multiplication

Two main ways of performing multiplication is neural network and the deep learning ▶

1. Element-wise multiplication

2. Matric multiplication (dot product)

there are two main rules that performing matrix multiplication needs to satisfy ▶

1. the inner dimensions must match :

* `(3,2) @ (3,2)` will not work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The result matrix will have the shape of outer dimensions :
* `(2,3) @ (3,2)` -> ndim `(2,2)`
* `(3,2) @ (2,3)` -> ndim `(3,3)`
❗here the @ is matmul



In [16]:
## Element wise matrix multiplication
tensor1 = torch.tensor([1,3,5])
print(tensor1)
print(f"Element wise Mul : {tensor1 * tensor1}" )

tensor([1, 3, 5])
Element wise Mul : tensor([ 1,  9, 25])


In [17]:
# matrix multiplication
torch.matmul(tensor1,tensor1)

tensor(35)

In [18]:
%%time
t = torch.tensor([1,2,3])
torch.matmul(t ,t)

CPU times: user 224 µs, sys: 0 ns, total: 224 µs
Wall time: 192 µs


tensor(14)

In [20]:
t1 = torch.matmul(torch.rand(3,2) , torch.rand(2,3))
print(f"{t1} \n shape : {t1.shape}")

tensor([[0.3649, 0.1432, 0.1492],
        [1.2050, 0.4854, 0.3935],
        [0.7411, 0.2913, 0.3004]]) 
 shape : torch.Size([3, 3])


In [27]:
## torch.mm(ten1 , ten2) `it is alias of torch.matmul`

## to transpose the tensor we use var.T
ten_b = torch.tensor([[1,2],[2,3],[3,4]])

print(torch.matmul(ten_b , ten_b.T))

tensor([[ 5,  8, 11],
        [ 8, 13, 18],
        [11, 18, 25]])


In [30]:
tensor  = torch.rand(size=(3,2))
tensor1 = torch.rand(size=(3,2))
print(tensor,  "\n" ,tensor1)

print(f"the original shape of the tensors is {tensor.shape} and {tensor1.shape}")
print(f"the tensors modification for matrix multiplication is {tensor.shape} and {tensor1.T.shape}")
print(f"the multiplication of {tensor.shape} and {tensor1.T.shape} is : \n")
print(f"{torch.matmul(tensor , tensor1.T)}")
output = torch.matmul(tensor , tensor1.T)
print(f"the shape of the output is {output.shape}")

tensor([[0.4009, 0.1354],
        [0.3331, 0.3647],
        [0.7286, 0.2597]]) 
 tensor([[0.7318, 0.1098],
        [0.2383, 0.6099],
        [0.2998, 0.9937]])
the original shape of the tensors is torch.Size([3, 2]) and torch.Size([3, 2])
the tensors modification for matrix multiplication is torch.Size([3, 2]) and torch.Size([2, 3])
the multiplication of torch.Size([3, 2]) and torch.Size([2, 3]) is : 

tensor([[0.3082, 0.1781, 0.2547],
        [0.2838, 0.3018, 0.4622],
        [0.5617, 0.3321, 0.4765]])
the shape of the output is torch.Size([3, 3])


## Finding the min, max, mean , sum , etc(tensor aggregation)


In [32]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
# find the minimum

torch.min(x ) , x.min()

(tensor(0), tensor(0))

In [36]:
#find the maximum

torch.max(x) , x.max()

(tensor(90), tensor(90))

In [35]:
# finding the mean - note: torch.mean() requires a tensor of float32 to work

torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [37]:
# find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [39]:
# finding the positional min and max or arg max and arg min

## find the position in tensor that has minimum with arg min
print(x.argmin())

##find the position in tensor that has maximum with arg max
print(x.argmax())

tensor(0)
tensor(9)


## reshapeing , stacking , squeezing and unsqueezing tensors

* reshaping - reshapes an input tensor to a defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple stacks on top of each other (vstack) or side by side (hstack)
* squeeze - removes all '1' dimensions from tensor
* unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [46]:
# create a tensor
import torch
x = torch.arange(1. ,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [47]:
x_reshape = x.reshape(6,2)
x_reshape , x_reshape.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [48]:
## change the view
z = x.view(3,4)
z , z.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [55]:
# stack the tensors on top of each other (v stack)
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked.shape , x_stacked

(torch.Size([4, 12]),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]))

In [56]:
# vstack
x_stacked = torch.vstack([x,x,x,x])
x_stacked.shape , x_stacked

(torch.Size([4, 12]),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]))

In [57]:
# stack the tensors on side by side of each other (hstack)
x_stacked = torch.hstack([x,x,x,x])
x_stacked.shape , x_stacked

(torch.Size([48]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  1.,  2.,
          3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,  1.,  2.,  3.,  4.,
          5.,  6.,  7.,  8.,  9., 10., 11., 12.,  1.,  2.,  3.,  4.,  5.,  6.,
          7.,  8.,  9., 10., 11., 12.]))

In [60]:
#Squeeze and Unsqueeze
# torch.squeeze() - removes all the `1` dimensions in the tensor
x_reshaped = x.reshape(1,12)
print(f" tensor : {x_reshaped}")
print(f" shape : {x_reshaped.shape}")

previous tensor : tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
previous shape : torch.Size([1, 12])


In [61]:
x_reshaped.squeeze() , x_reshaped.squeeze().shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [64]:
# torch.usqueeze() adds an single dimension to an target tensor at a  specific dim (dimension)
print(f" the previous target : {x_reshaped.squeeze()}")
print(f" the previous target shape : {x_reshaped.squeeze().shape}")

## add an extra dimension
print(f" the unsqueezed target : {x_reshaped.squeeze().unsqueeze(dim=0)}")
print(f" the unsqueezed target shape : {x_reshaped.squeeze().unsqueeze(dim=0).shape}")
#

 the previous target : tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
 the previous target shape : torch.Size([12])
 the unsqueezed target : tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
 the unsqueezed target shape : torch.Size([1, 12])


In [ ]:
## permute - > torch.permute(var , (i , i ,i)) , rearranging the dimensions of a target tensor in a specified order

x = torch.randn(2,3,5)
print(f"size is {x.size()}")

torch.permute(x,(2,0,1)).size()

In [68]:
x_original = torch.rand(size=(224,224,3)) # [height , width, colour channels]

# permute the original tensor
x_permuted = x_original.permute(2,0,1) #shifts the axis 0-> 1 , 1->2, 2-> 0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}") #[colour_channels, height , width]

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [72]:
 # x_original[0,0,0] = 2323

In [73]:
# x_permuted[0,0,0]

Indexing (selecting data from tensors)
indexing with pytorch is similiar to indexing with Numpy

In [77]:
# indexing
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
x[0][2][2]

# You can also use ":" to select all of the target dimension
print(x[:,0])

tensor([[1, 2, 3]])


In [88]:
## get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension

x[0 , 0 ,:]

tensor([1, 2, 3])

Numpy python Relation

In [90]:
# numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array ,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
# change the value of array , what will this do to 'tensor' ?
array = array + 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [95]:
# tensor to Numpy array
tensor = torch.ones(7).type(torch.int64)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1, 1, 1, 1, 1, 1, 1]), array([1, 1, 1, 1, 1, 1, 1]))

## reproducability (random nums out of random)
in short how a neural network learns:

`start with random numbers -> tensor operations -> update the nums -> representation -> again -> again ...`

to reduce the randomness in the neural networks and pytorch comes with concept of a random seed

Essentially what the random seed does is "flavour" the randomness

In [96]:
import torch

#create two random tensors

rand_a = torch.rand(3,4)
rand_b = torch.rand(3,4)

print(rand_a)
print(rand_b)
print(rand_a == rand_b)

tensor([[0.0522, 0.0085, 0.9133, 0.5524],
        [0.0280, 0.0196, 0.7375, 0.3379],
        [0.9234, 0.1250, 0.1005, 0.4186]])
tensor([[0.6876, 0.1122, 0.0938, 0.8101],
        [0.6609, 0.8808, 0.6276, 0.3753],
        [0.5358, 0.6721, 0.1319, 0.8971]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [99]:
# let's make some reproducable random tensors
import torch


# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
rand_d = torch.rand(3,4)

print(rand_c)
print(rand_d)
print(rand_c == rand_d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [4]:
# setup device agnostic code
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# count of devices
torch.cuda.device_count()

1